### ISSUE TITLE
The Archeological Dig

### ISSUE THREAD

**Issue by Huymnsel** [DW8030/Civ6-mod#10]
The locate mod error is just kinda annoying when it keeps reporting yellow problem with this one. Maybe just make it erase all base tile yields and give some "types" of artifacts that provide different bonuses? (like one that gives faith, one that gives culture, etc...)

**Comment by DW8030** [comment]
You're right, I should give it a stat to remove the yellow error. The Archaeological now gives +1 Culture and the Preserve gives +1 Gold.

**Comment by Huymnsel** [comment]
Wait a sec though, are they gonna be placed on-map? I'm pretty sure they are intended to be tile improvements so why not give them their proper "civ 6" stats?

**Comment by DW8030** [comment]
They don't have stats in Civ6. I gave them a very small stat bonus to remove the yellow errors (which are indeed quite annoying).

**Comment by Huymnsel** [comment]
Hmm, I can see it, Preserves are still in freestyle for now, maybe this is the best solution. Will you close this issue right away or leave it to see if we have any better solution in the future?

**Comment by DW8030** [comment]
There will probably a better solution in the future, but not now. I'll close this issue, a new one can be opened when needed.
