### ISSUE TITLE
Circular dependency between Factory and power plants

### ISSUE THREAD

**Issue by de-code** [DW8030/Civ6-mod#15]
Thanks for providing the mod.

The Factory depends on "2 Power". But all of the power plants depend on Factory.
Therefore it seems impossible to build a Factory or a power plant?

**Comment by DW8030** [comment]
You're right. In Civ6, they give additional production when powered but I messed up the resource requirements fot Unciv gameplay. I'll fix that later this day.

**Comment by de-code** [comment]
Great. I suppose there could be an additional "Powered Factory" to give the extra bonus. Although you have the production bonus on the power plant already.
