### ISSUE TITLE
Other Civs

### ISSUE THREAD

**Issue by raen1978** [DW8030/Civ6-mod#16]
Are you implementing the other remaining civs from the last DLC´s, for instance adding Portugal?

Anyway, many thanks for this fantastic mod!

**Comment by DW8030** [comment]
Hello raen1978,

Thank you for your question. I tried to add Portugal and some other nations at some point, but the nations from more recent expansion sets have often quite specialized abilities and I figured it would not really be possible to implement those in a good way. I'm currently not actively developing the mod anymore, maybe I should look at it a again to see if more things are possible within the game mechanics now.
