### ISSUE TITLE
Error in game.

### ISSUE THREAD

**Issue by Zakhar-Hadanovich** [DW8030/Civ6-mod#47]
Hello, after the last update of the mod, I can't start a new batch with it, it gives an error. (screenshot attached)
![Screenshot_2023-01-26-11-56-07-560_com unciv app](https://user-images.githubusercontent.com/123335891/214809136-73c0654f-5998-43fa-96b7-12095d01c553.jpg)tell me the solution, please.
If you suddenly fail to go to the image, then the game writes that for ordinary roads a wheel is required that does not exist. and also the railway requires railway technology that does not exist. Because of this error, it is not possible to start the game.

**Comment by DW8030** [comment]
My fault, I'll fix it immediately.

**Comment by Zakhar-Hadanovich** [comment]
Спасибо.
